version: "3.8"
services:
  db:
    image: postgres:latest
    container_name: compra-contenedor
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4884
      POSTGRES_DB: Microservicios
    ports:
      - "5432:5432"
    networks:
      - ms-network
  ms-buys:
    build:
      context: ./ms-buys
      dockerfile: Dockerfile
    image: ms-buys:latest
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    volumes:
      - ./ms-buys:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - ms-network
      